### ISSUE TITLE
The latest version can not load fringe-mode

### ISSUE THREAD

**Issue by arkhan** [xiaohanyu/oh-my-emacs#107]
I download the lastest version for oh-my-emacs, but when run emacs, I get this warning:
Warning (initialization): An error occurred while loading `~/.emacs.d/init.el':
 Symbol's function definition is void: fringe-mode
 To ensure normal operation, you should investigate and remove the cause of the error in your initialization file.  Start Emacs  with the `--debug-init' option to view a complete error backtrace.

**Comment by SASDOE** [comment]
Hi,

Just cloned, I am having the same issue.

OS is Archlinux (3.18.6-1-ARCH), emacs 24.4.1.

**Comment by SASDOE** [comment]
Problem is I had installed emacs-nox.
I believe this had to be the same issue as arkhan and suppose you can close the issue.

**Comment by xiaohanyu** [comment]
Hey, as I know, `fringe-mode` is a feature for gui emacs, so if you use emacs-nox, just disable `fringe-mode` and it should work.

**Comment by cloudkitsch** [comment]
@xiaohanyu emacs has changed the way I think in general-- which if not for oh-my-emacs I would not have ever bothered; that said I've gotten used to working through problems, on a case by case basis. That said, I've picked up a few books along the way and a new found interest in lisp in general. It's not so bad, comment this region, move on.

**Comment by cloudkitsch** [comment]
or you know.. 

➜  core git:(master) sudo emerge app-xemacs/xemacs-packages-all
Calculating dependencies... done!
>>> Verifying ebuild manifests
>>> Emerging (1 of 120) media-libs/audiofile-0.3.6-r1::gentoo
>>> Jobs: 0 of 120 complete, 1 running              Load avg: 0.58, 0.21, 0.11

whatever will let you move on to real work ;)
