### ISSUE TITLE
Ack and a half mirror doesn't exist anymore.

### ISSUE THREAD

**Issue by pekhee** [xiaohanyu/oh-my-emacs#124]
el-get cannot clone https://github.com/emacsmirror/ack-and-a-half

**Comment by xuchunyang** [comment]
The `ack-and-a-half` package is not maintained anymore, its author has confirmed this, see https://github.com/jhelwig/where-are-my-repos

A good alternate is https://github.com/leoliu/ack-el.

**Comment by xiaohanyu** [comment]
Fixed, thanks @xuchunyang very much. Sorry for my late response.
