### ISSUE TITLE
Problem installing slime on OS X 10.10

### ISSUE THREAD

**Issue by estebanrules** [xiaohanyu/oh-my-emacs#128]
I get the following error when oh-my-emacs is setting up slime:

```makeinfo slime.texi
slime.texi:6: warning: unrecognized encoding name `UTF-8'.
slime.texi:6: Unknown command `codequoteundirected'.
slime.texi:7: Unknown command `codequotebacktick'.
makeinfo: Removing output file `/Users/esteban/.emacs.d/el-get/slime/doc/slime.info' due to errors; use --force to preserve.
make: *** [slime.info] Error 1
--force```

**Comment by xiaohanyu** [comment]
Ah, you're a lazy guy, ^_^

https://github.com/xiaohanyu/oh-my-emacs/issues/85
https://github.com/xiaohanyu/oh-my-emacs/issues/120

https://github.com/xiaohanyu/oh-my-emacs/commit/140825dc0d47c84a91cbba043e0a4fe7246f7d95

**Comment by estebanrules** [comment]
Thanks.  That fixed it.
