### ISSUE TITLE
Redundant closing braces after expansion of a snippet

### ISSUE THREAD

**Issue by Plypy** [xiaohanyu/oh-my-emacs#129]
When I was trying to use the snippets in CPP, it will insert redundant closing braces for some snippets. Like `main` `fori`, after the expansion, the result will go like below
```
int main(#cursor#)int argc, char *argv[])
{
    
    return 0;
}
```

Thouth it works fine for `for`.

**Comment by Plypy** [comment]
This seems to be a very basic function, shouldn' there be anyone else who has noticed that as well, or just me???

**Comment by xiaohanyu** [comment]
What you mean redundant? Seems this is a problem of yasnippet, not oh-my-emacs

**Comment by Plypy** [comment]
You see there is one extra closing bracket inputted after the cursor, and lead to `[yas] Snippet 1 exited.`.

I think that the closing bracket is generated by some others. But being a new Emacs user, I'm not sure.

**Comment by xiaohanyu** [comment]
I tried but this bug didn't reproduced on my ome, maybe you can turn off `smartparens-mode` and try again.

**Comment by Plypy** [comment]
It worked, thanks!

**Comment by xuchunyang** [comment]
@Plypy consider closing this issue?
