### ISSUE TITLE
Failed to parse chinese gbk coded file in ubuntu

### ISSUE THREAD

**Issue by zhenghub** [xiaohanyu/oh-my-emacs#132]
I wrote some notes in Chinese with org-mode in windows, and I could read and edit it well with default emacs in ubuntu. However, when enabling oh-my-emacs, this note file turns unreadable codes in emacs.
I used the "describe-coding-system" function in both configurations in the note's buffer.
```javascript
| The origin emacs shows                                                | The oh-my-emacs shows                                                 |
|-----------------------------------------------------------------------+-----------------------------------------------------------------------|
| Coding system for saving this buffer:                                 | Coding system for saving this buffer:                                 |
| c -- chinese-gbk-dos (alias: gbk-dos cp936-dos windows-936-dos)       | 1 -- iso-latin-1-dos (alias: iso-8859-1-dos latin-1-dos)              |
|                                                                       |                                                                       |
| Default coding system (for new files):                                | Default coding system (for new files):                                |
| U -- utf-8-unix (alias: mule-utf-8-unix)                              | U -- utf-8-unix (alias: mule-utf-8-unix)                              |
|                                                                       |                                                                       |
| Priority order for recognizing coding systems when reading files:     | Priority order for recognizing coding systems when reading files:     |
| 1. utf-8 (alias: mule-utf-8)                                          | 1. utf-8 (alias: mule-utf-8)                                          |
| 2. chinese-gbk (alias: gbk cp936 windows-936)                         | 2. iso-2022-7bit                                                      |
| 3. iso-2022-cn (alias: chinese-iso-7bit)                              | 3. iso-latin-1 (alias: iso-8859-1 latin-1)                            |
| 4. chinese-big5 (alias: big5 cn-big5 cp950)                           | 4. iso-2022-7bit-lock (alias: iso-2022-int-1)                         |
| 5. chinese-iso-8bit (alias: cn-gb-2312 euc-china euc-cn cn-gb gb2312) | 5. iso-2022-8bit-ss2                                                  |
| 6. iso-2022-7bit                                                      | 6. emacs-mule                                                         |
| 7. iso-2022-8bit-ss2                                                  | 7. raw-text                                                           |
| 8. emacs-mule                                                         | 8. chinese-big5 (alias: big5 cn-big5 cp950)                           |
| 9. raw-text                                                           | 9. chinese-iso-8bit (alias: cn-gb-2312 euc-china euc-cn cn-gb gb2312) |
```
It seems like some encoding priority order should be customized but I don't know how.

**Comment by xiaohanyu** [comment]
Hey, sorry for my late response. Could you please show me you linux's locale?

You can type `locale` in your terminal to get this.

Maybe this is a problem of the file. The encoding of your file is not UTF-8 in Linux. you can check this by `file filename` in terminal to get the file encoding.

**Comment by zhenghub** [comment]
Thank you for telling me about `locale` and `file` command. I'm not good enough at Linux.
`locale` result:
>> LANG=zh_CN.UTF-8
LANGUAGE=zh_CN:zh
LC_CTYPE="zh_CN.UTF-8"
LC_NUMERIC="zh_CN.UTF-8"
LC_TIME="zh_CN.UTF-8"
LC_COLLATE="zh_CN.UTF-8"
LC_MONETARY="zh_CN.UTF-8"
LC_MESSAGES="zh_CN.UTF-8"
LC_PAPER="zh_CN.UTF-8"
LC_NAME="zh_CN.UTF-8"
LC_ADDRESS="zh_CN.UTF-8"
LC_TELEPHONE="zh_CN.UTF-8"
LC_MEASUREMENT="zh_CN.UTF-8"
LC_IDENTIFICATION="zh_CN.UTF-8"
LC_ALL=


`file` result:
>>hadoop.org: ISO-8859 text, with CRLF line terminators


Yes, I know it's not in UTF-8. But I have many files of which the encoding is not UTF-8 and may be gbk or iso-8859. Since I have to handle many files from other people it's too hard to ensure all the files to be in UTF-8. Would it be good to configure the Emacs to auto recognize the encoding of a file?

**Comment by xiaohanyu** [comment]
Hey, 

After an hour of investigation work, finally I got a workaround for your issue, just add 

```
(set-coding-system-priority 'utf-8 'chinese-gb18030)
```

to your `.emacs` file and then your coding priority with changes:

```
Priority order for recognizing coding systems when reading files:
  1. utf-8 (alias: mule-utf-8)
  2. chinese-gb18030 (alias: gb18030)
  3. iso-2022-7bit 
  4. iso-2022-7bit-lock (alias: iso-2022-int-1)
  5. iso-2022-8bit-ss2 
  6. emacs-mule 
  7. raw-text 
  8. iso-2022-jp (alias: junet)
  9. in-is13194-devanagari (alias: devanagari)
  10. chinese-iso-8bit (alias: cn-gb-2312 euc-china euc-cn cn-gb gb2312)
  11. utf-8-auto 
  12. utf-8-with-signature 
  13. utf-16 
  14. utf-16be-with-signature (alias: utf-16-be)
  15. utf-16le-with-signature (alias: utf-16-le)
  16. utf-16be 
  17. utf-16le 
  18. japanese-shift-jis (alias: shift_jis sjis)
  19. chinese-big5 (alias: big5 cn-big5 cp950)
  20. undecided 
```

However, I can't put this into oh-my-emacs since oh-my-emacs is not only for chinese users. You can put this in `custom.el` or `your_username.el` under `.emacs.d` directory.

I'll document this.

Encoding is really a complex topic, check https://www.gnu.org/software/emacs/manual/html_node/emacs/International.html#International for technical internal details.

**Comment by xiaohanyu** [comment]
Tips: 

1. you can always switch encoding by `M-x revert-buffer-with-coding-system`.
2. you can always set file-local or directory-local variables to change encoding settings for a file or files in a directory, https://www.gnu.org/software/emacs/manual/html_node/emacs/Directory-Variables.html

**Comment by zhenghub** [comment]
Thanks a lot! It did solve the problem. Sorry for cost your time but thanks!
