### ISSUE TITLE
Fail to install evil plugin(Solved)

### ISSUE THREAD

**Issue by allenwoods** [xiaohanyu/oh-my-emacs#134]
The evil-mode repository given in el-get recipe file (git://gitorious.org/evil/evil.git) can't be accessed in my case. Git error:
>fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.
Please make sure you have the correct access rights and the repository exists.

By using 
>M-x el-get-find-recipe-file: evil

I change the line with **:url** in the file into
>:url "https://github.com/emacsmirror/evil

and then the initialization continued without further error. I'm not sure if there is a problem in el-get/evil or just my network environment in mainland China. 

I hope this piece of information could help other newbies like me.
Thanks for the great work! @xiaohanyu

**Comment by xuchunyang** [comment]
something wrong with Gitorious, see https://gitorious.org/evil

**Comment by allenwoods** [comment]
@xuchunyang yes, that's a 500 Internal server error. I thought it was due to the GFW earlier:joy:

**Comment by xuchunyang** [comment]
hmm, according to https://lists.ourproject.org/pipermail/implementations-list/2015-March/002153.html
you can use HTTP(S) instead of git protocol.

**Comment by xiaohanyu** [comment]
Thanks @xuchunyang !

**Comment by rej156** [comment]
Thanks so much @xuchunyang !
