### ISSUE TITLE
Org-mode installation problem

### ISSUE THREAD

**Issue by xiaohanyu** [xiaohanyu/oh-my-emacs#148]
Currently, oh-my-emacs adopt org-mode 8.x instead of the builtin org-mode 7.x, however, the default installation of org-mode installation has one problem---the `(org-version)` function returns empty version string, while normal `(org-version)` should return a proper version string. 

Some packages, such as org2blog depends on this version string, lacking this will caused org2blog failed to install.

Ref: #147

**Comment by hujianxin** [comment]
@xiaohanyu 我看到`oh-my-emacs`里面已经更新org了阿，为什么还会出现这个问题呢。。。
