### ISSUE TITLE
Unable to find editorconfig executable.  Styles will not be applied.

### ISSUE THREAD

**Issue by libchaos** [xiaohanyu/oh-my-emacs#155]
How to solve it?waiting online ,thanks

**Comment by xuchunyang** [comment]
How about read some documentation first? https://github.com/xiaohanyu/oh-my-emacs/blob/master/core/ome-basic.org#editorconfig

**Comment by greasynose** [comment]
The problem will be solved after you  install the editorconfig. see instruction on http://editorconfig.org/.
