### ISSUE TITLE
el-get flycheck error: languages.texi:577: Unmatched `@end'

### ISSUE THREAD

**Issue by account-archived-270316** [xiaohanyu/oh-my-emacs#158]
the installation got stuck at

```
/Users/a/.emacs.d/el-get/flycheck/doc//languages.texi:577: Unmatched `@end'.
/Users/a/.emacs.d/el-get/flycheck/doc//languages.texi:715: Unknown command `sma\
llindentedblock'.
/Users/a/.emacs.d/el-get/flycheck/doc//languages.texi:720: Unmatched `@end'.
makeinfo: Removing output file `doc/flycheck.info' due to errors; use --force t\
o preserve.
```

<img width="651" alt="screen shot 2015-09-14 at 11 37 38 pm" src="https://cloud.githubusercontent.com/assets/10269911/9854171/f6cf27dc-5b39-11e5-9182-e66ceeabed27.png">

**Comment by xiehao** [comment]
Same error

**Comment by zhyy1314** [comment]
Hi, how is it going? I have the same problem, and want to get your help. Thanks.

**Comment by zhyy1314** [comment]
Hi, how is it going? I met the same problem, and want to ask for help. Thanks.

**Comment by xiehao** [comment]
@zhyy1314 Still hasn't solved yet.:(
