### ISSUE TITLE
auto-complete-mode not enable, popup too long

### ISSUE THREAD

**Issue by cuiruodevideo** [xiaohanyu/oh-my-emacs#164]
![toolong](https://cloud.githubusercontent.com/assets/5548261/11992917/5c849fe6-aa66-11e5-8dd2-a452a88519bf.png)
![auto-complete-mode](https://cloud.githubusercontent.com/assets/5548261/11992923/69a42a2a-aa66-11e5-911e-b898007fb513.png)

**Comment by syohex** [comment]
You can configure max width of popup by `ac-max-width` as below.

```lisp
(setq ac-max-width 0.5)
```

**Comment by cuiruodevideo** [comment]
nice, Thank you so much!

**Comment by cuiruodevideo** [comment]
![2015-12-29 17 20 49](https://cloud.githubusercontent.com/assets/5548261/12032202/977a8d7a-ae50-11e5-85de-1cc908502567.png)
[auto-complete-mode not enable]
我在使用elpy的时候又对jedi进行了配置，
http://tkf.github.io/emacs-jedi/latest/#manual-install
在我的init.el中加入了这句
(add-hook 'python-mode-hook 'jedi:setup)
导致 auto-complete-mode not enable.

but, i don't kown why.
------------------------------------------------
达到上图的目的我用了company-quickhelp
参考: https://github.com/jorgenschaefer/elpy/issues/459
