### ISSUE TITLE
current version do not support c++11 features

### ISSUE THREAD

**Issue by cg82616424** [xiaohanyu/oh-my-emacs#166]
auto-complete-clang and flycheck config do not support c++11 features, can you tell me how to modify?

**Comment by xiaohanyu** [comment]
@cg82616424 Maybe you can add some extra parameters to auto-complete-clang? Actually, auto-complete-clang just call clang to get an output, and parse the output to a list of completions.

Check https://github.com/brianjcj/auto-complete-clang/blob/master/auto-complete-clang.el#L57-L69 for source code.

In oh-my-emacs, I think you can add something like `-std=c++11` to https://github.com/xiaohanyu/oh-my-emacs/blame/master/modules/ome-cc.org#L234.

However, this project is dead. I've no extra time to maintain it anymore, sorry.
