### ISSUE TITLE
For java part, I think eclimd should not be used in emacs

### ISSUE THREAD

**Issue by caoyuanqi** [xiaohanyu/oh-my-emacs#168]
The eclimd in emacs is a little buggy when it is running inside emacs, I think we should run it outside emacs, I  can not successfully run it inside emacs without crash emacs

**Comment by xiaohanyu** [comment]
@caoyuanqi In my opinion, eclipse and eclimd both have some weird bugs which is hard to track and handle. I prefer to use Jetbrains' IDE to write Java code when necessary. And use eclimd as a simple experimental tool.

**Comment by caoyuanqi** [comment]
@xiaohanyu Yes, I agree with you, java is not a friend of Emacs
