### ISSUE TITLE
URL is nil, can't decide if it's safe to install package rainbow-mode

### ISSUE THREAD

**Issue by cuiruodevideo** [xiaohanyu/oh-my-emacs#169]
Debugger entered: ((cl-assertion-failed (stringp URL) "URL is nil, can't decide if it's safe to install package '%s'"))
  cl--assertion-failed((stringp URL) "URL is nil, can't decide if it's safe to install package '%s'" nil (rainbow-mode))
  el-get-insecure-check(rainbow-mode nil)
  el-get-elpa-install(rainbow-mode nil el-get-post-install)
  el-get-do-install(rainbow-mode)
  el-get-init-and-install(nil)
----------------------------------------------------------------------
url: http://elpa.gnu.org/packages/rainbow-mode.html
----------------------------------------------------------------------
how can i solve it?
---------------------------------------------------------------------
https://github.com/dimitri/el-get/issues/2467
there have same error.

**Comment by xiaohanyu** [comment]
It seems that el-get issue has fixed this problem.
