### ISSUE TITLE
installation bug on mac os 10.9

### ISSUE THREAD

**Issue by shpeacelover** [xiaohanyu/oh-my-emacs#37]
Hi, 

This is the error message I got when I tried to use your "oh-my-emacs". I am using MAC OS 10.9 now. 

```
Debugger entered--Lisp error: (void-function fringe-mode)
  (fringe-mode 4)
  eval-buffer(#<buffer  *load*-106367> nil "/Users/sun/.emacs.d/core/ome-gui.el" nil t)  ; Reading at buffer position 334
  load-with-code-conversion("/Users/sun/.emacs.d/core/ome-gui.el" "/Users/sun/.emacs.d/core/ome-gui.el" nil nil)
  load("/Users/sun/.emacs.d/core/ome-gui.el" nil nil t)
  load-file("/Users/sun/.emacs.d/core/ome-gui.el")
  org-babel-load-file("/Users/sun/.emacs.d/core/ome-gui.org")
  (if header-or-tags (progn (let ((--dolist-tail-- header-or-tags) header-or-tag) (while --dolist-tail-- (setq header-or-tag ($
  (let ((module-name (file-name-base module)) (file (expand-file-name (if (string-match "ome-.+.org" module) module (format "o$
  ome-load("core/ome-gui.org")
  eval-buffer(#<buffer  *load*-830434> nil "/Users/sun/.emacs.d/ome.el" nil t)  ; Reading at buffer position 6584
  load-with-code-conversion("/Users/sun/.emacs.d/ome.el" "/Users/sun/.emacs.d/ome.el" nil nil)
  load("/Users/sun/.emacs.d/ome.el" nil nil t)
  load-file("/Users/sun/.emacs.d/ome.el")
  org-babel-load-file("/Users/sun/.emacs.d/ome.org")
```

Please help take a look at it. 

Thanks,
Steven

**Comment by jefferai** [comment]
Can we reopen this? Fresh emacs installation, fresh oh-my-emacs, same bug.

Yes, I'm on OSX. I realize that commenting out the line above will probably fix it, but it seems like there ought to be a better (automatic) way.

**Comment by xiaohanyu** [comment]
@jefferai What's your emacs's version?

**Comment by jefferai** [comment]
@xiaohanyu The version was 24.4 from Homebrew. However, I since tried emacs-24.4-mac-5.2 (see https://github.com/railwaycat/homebrew-emacsmacport/blob/master/Formula/emacs-mac.rb) and it doesn't seem to have this problem. I could use some confirmation though, in case something else in my setup changed while I was trying to get past these errors.

**Comment by cloudkitsch** [comment]
issue is the same on my gentoo setup, probably has to do with how emacs was compiled
