### ISSUE TITLE
Flycheck install fails

### ISSUE THREAD

**Issue by IshmaelBelghazi** [xiaohanyu/oh-my-emacs#47]
FlyCheck install fails. I am running ubuntu 12.04 TLS 64bit. Here is the output:

```
/home/stark/.emacs.d/el-get/flycheck/doc//flycheck.texi:1683: Next field of node `Extending checkers' not pointed to (perhaps incorrect sectioning?).
/home/stark/.emacs.d/el-get/flycheck/doc//flycheck.texi:1700: This node (Examples) has the bad Prev.
/home/stark/.emacs.d/el-get/flycheck/doc//flycheck.texi:1683: Prev field of node `Extending checkers' not pointed to.
/home/stark/.emacs.d/el-get/flycheck/doc//flycheck.texi:1667: This node (Option filters) has the bad Next.
makeinfo: Removing output file `/home/stark/.emacs.d/el-get/flycheck/doc/flycheck.info' due to errors; use --force to preserve.

```

**Comment by erson** [comment]
brew install texinfo (end line --> /usr/local/Cellar/texinfo/5.2: 396 files, 8.1M)

λ which makeinfo
/usr/bin/makeinfo

λ /usr/bin/makeinfo --version
makeinfo (GNU texinfo) 4.8

λ sudo mv /usr/bin/makeinfo /usr/bin/makeinfo.bk
λ sudo ln -s /usr/local/Cellar/texinfo/5.2/bin/makeinfo /usr/bin/makeinfo

start emacs again and wait for progress to end.
