### ISSUE TITLE
Unable to install on Mac (fails at `makeinfo slime.tex`)

### ISSUE THREAD

**Issue by srid** [xiaohanyu/oh-my-emacs#85]
despite running `brew install coreutils texinfo`, this is what I see on OS X 10.10:

```
cat ../ChangeLog | \
    sed -ne '/^[0-9]/{s/^[^ ]* *//; s/ *<.*//; p;}' | \
    sort | \
    uniq -c | \
    sort -nr| \
    sed -e 's/^[^A-Z]*//' | \
    awk -f texinfo-tabulate.awk \
    > contributors.texi
makeinfo slime.texi
slime.texi:6: warning: unrecognized encoding name `UTF-8'.
slime.texi:6: Unknown command `codequoteundirected'.
slime.texi:7: Unknown command `codequotebacktick'.
makeinfo: Removing output file `/Users/srid/.emacs.d/el-get/slime/doc/slime.info' due to errors; use --force to preserve.
make: *** [slime.info] Error 1
```

**Comment by vydd** [comment]
For **macports** users:

What `brew link texinfo --force` does is that, to my understanding, it just symlinks stuff installed using brew to standard system directories. You can do the same manually. By looking at `~/.emacs.d/el-get/slime/doc/Makefile`, you'll see that slime docs need texi2dvi, dvips, makeinfo and texi2html. So, running this as root:

Go to `/usr/bin`

    # cd /usr/bin

Backup the current binaries. Don't worry if some of the files don't exist.

    # mv texi2dvi texi2dvi.old
    # mv makeinfo makeinfo.old
    # mv dvips dvips.old
    # mv texi2html texi2html.old

Assuming /opt/local is where you keep your macports installs, symlink the following:
    
    # ln -s /opt/local/bin/texi2dvi texi2dvi
    # ln -s /opt/local/bin/dvips dvips
    # ln -s /opt/local/bin/makeinfo makeinfo
    # ln -s /opt/local/bin/texi2html texi2html

That should be it. Restart emacs.

If it still fails, I guess you'll need to:

    # mv /usr/share/texinfo /usr/share/texinfo.old
    # ln -s /opt/local/share/texinfo /usr/share/texinfo

Hope it helps.

**Comment by xiaohanyu** [comment]
@vydd Thanks! This really helps for macports user. I think I should write this to oh-my-emacs.

**Comment by elliottslaughter** [comment]
Just FYI, overwriting links in `/usr/bin` is generally considered bad practice on Mac OS X and can cause problems. In this particular case, you don't even need to do this. You can just:

    cd ~/.emacs.d/el-get/slime/doc
    /usr/local/Cellar/texinfo/5.2/bin/makeinfo slime.texi # or wherever your makeinfo is located

This is sufficient to make Emacs stop complaining until you update slime (and then only if slime.texi changes).

If you want to make this more permanent, you can just stick the Homebrew installation directory on PATH. There is absolutely no need to go writing stuff into system directories.
