### ISSUE TITLE
cannot open load file: helm-autoloads

### ISSUE THREAD

**Issue by paomian** [xiaohanyu/oh-my-emacs#91]
when i open my emacs, i get this error,then,i go into .emacs.d and find helm is exist,so i google it,but i can not find anything.something say that it is not complier,when i run make, i get the not find cl-lib,but i can find it,so how to fix it?

**Comment by chuchao333** [comment]
@xiaohanyu any idea why I am still hitting this issue after remove the whoel el-get dir and restart? A manual 'make' under el-get/helm/ solved the issue though.
